config/routes.rb
Rails.application.routes.draw do
  resources :projects

  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, tasks_attributes: [:id, :description, :done, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NestedFormExample" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">NestedFormExample</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->
      <br>
      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>

  <h2>Tasks</h2>

  <%= f.fields_for :tasks do |task| %>
    <%= render 'task_fields', :f => task %>
  <% end %>

  <div class="links">
    <%= link_to_add_association 'add task', f, :tasks, :class => 'btn btn-primary' %>
  </div>

  <br>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', projects_path, :class => 'btn btn-default' %>

<% end %>

app/views/projects/_task_fields.html.erb
<div class="nested-fields">
  <div class="jumbotron">
    <div class="form-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="checkbox">
        <label><%= f.check_box :done %> Done</label>
      </div>
    </div>

    <%= link_to_remove_association "remove task", f, :class => 'btn btn-danger' %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1><%= @project.name %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td>
          <%= link_to "Edit", edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Delete", project_path(project), :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New", new_project_path, :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <h1><%= @project.name %></h1>
</div>


<% @project.tasks.each do |task| %>
  <div class="well">
    <%= task.description %>
    <br>
    <strong>Is it done?</strong>
    <%= task.done? ? 'Yes' : 'No' %>
  </div>
<% end %>

<br>

<%= link_to "Back", projects_path, :class => 'btn btn-default'  %>
<%= link_to "Edit", edit_project_path(@project), :class => 'btn btn-default' %>
<%= link_to "Delete", project_path(@project), :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>